# Generated by Django 4.2.7 on 2024-01-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0002_alter_userdata_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='tel',
            field=models.CharField(default='', max_length=20),
        ),
    ]
