# Generated by Django 4.2.7 on 2024-01-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0003_alter_userdata_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
