# Generated by Django 4.2.7 on 2024-01-14 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=50)),
                ('charger', models.CharField(default='', max_length=50)),
                ('status', models.IntegerField(choices=[(1, '見積もり中'), (2, '担当者選択中'), (3, '作業中'), (4, '作業終了')], default=1)),
                ('deadline', models.DateField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_client_unread', models.BooleanField(default=False)),
                ('is_admin_unread', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
