# Generated by Django 4.2.7 on 2024-01-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='original_image_url',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='job',
            name='result_image_url',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
