# Generated by Django 4.2.7 on 2024-07-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_end_original_image_url_job_end_result_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='delivery',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='job',
            name='pickup',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='job',
            name='work_details',
            field=models.CharField(default='', max_length=250),
        ),
    ]
